apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app-deploy
  labels:
    app: healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-app-container
        image: junaidadil/healthcare-app
        ports:
        - containerPort: 8082
        volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true 
  volumes:
        - name: config-volume
          configMap:
            name: healthcare-app-config
            items:
              - key: ENV_VAR1
                path: ENV_VAR1
              - key: ENV_VAR2
                path: ENV_VAR2
  spec:
  template:
    spec:
      containers:
        - name: healthcare-app-container
          image: junaidadil/healthcare-app
          envFrom:
            - secretRef:
                name: my-secret
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-np-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app

  type: NodePort
  ports:
  - nodePort: 31020  
    port: 8082
    targetPort: 8082
